// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/dashboard": {
    params: {};
  };
  "/tasks/:taskId": {
    params: {
      "taskId": string;
    };
  };
  "/today": {
    params: {};
  };
  "/upcoming": {
    params: {};
  };
  "/projects": {
    params: {};
  };
  "/archive": {
    params: {};
  };
  "/trash": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/dashboard" | "/tasks/:taskId" | "/today" | "/upcoming" | "/projects" | "/archive" | "/trash";
  };
  "./routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "./routes/dashboard.tsx": {
    id: "routes/dashboard";
    page: "/dashboard";
  };
  "./routes/task.tsx": {
    id: "routes/task";
    page: "/tasks/:taskId";
  };
  "./routes/today.tsx": {
    id: "routes/today";
    page: "/today";
  };
  "./routes/upcoming.tsx": {
    id: "routes/upcoming";
    page: "/upcoming";
  };
  "./routes/projects.tsx": {
    id: "routes/projects";
    page: "/projects";
  };
  "./routes/archive.tsx": {
    id: "routes/archive";
    page: "/archive";
  };
  "./routes/trash.tsx": {
    id: "routes/trash";
    page: "/trash";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/home": typeof import("./app/./routes/home.tsx");
  "routes/dashboard": typeof import("./app/./routes/dashboard.tsx");
  "routes/task": typeof import("./app/./routes/task.tsx");
  "routes/today": typeof import("./app/./routes/today.tsx");
  "routes/upcoming": typeof import("./app/./routes/upcoming.tsx");
  "routes/projects": typeof import("./app/./routes/projects.tsx");
  "routes/archive": typeof import("./app/./routes/archive.tsx");
  "routes/trash": typeof import("./app/./routes/trash.tsx");
};